### ISSUE TITLE
Замечания по работе

### ISSUE THREAD

**Issue by AndriiLitvin** [Mortehay/Mortehay.github.io#1]
Визуально: http://joxi.ru/vAWZzP3sJgg92W 
По коду: 
1)<div id="left"></div> - зачем он? Чтоб выровнять блок по центру использйуй margin: 0 auto;
2)<div id="center"></div> -  здесь условие вроди не стояло делать резиновою верстку, размеры в пикселях. ну если делаешь в % то уже все делай в них.
3)  У самого блока с контентом нет  border-radius и box-shadow
4) Размеры картинки не соответствуют макету.
5) <div id="right"></div>-зачем?
6) Используй class а не id, и названия классов должны быть говорящие.
7) все отступы делаем padding и  margin.

**Comment by Mortehay** [comment]
пожалуйста поясните замечания:  
1. "1)
        - зачем он? "  - не понятно, что под этим замечанием скрывается
2.  "4) Размеры картинки не соответствуют макету."  в задании не был указан размер фотки(может я пропустил)
3. "5)
-зачем?  "  - не понятно, что под этим замечанием скрывается

**Comment by AndriiLitvin** [comment]
Сори не досмотрел. сейчас все будет.

**Comment by AndriiLitvin** [comment]
По коду:
1) &#60;div id="left"&#62;  &#60;/div&#62;  - зачем он? Чтоб выровнять блок по центру используй margin: 0 auto;
2) &#60;div id="center"&#62;  &#60;/div&#62;  -  здесь условие вроди не стояло делать резиновою верстку, размеры в пикселях. ну если делаешь в % то уже все делай в них.
3)  У самого блока с контентом нет  border-radius и box-shadow
4) Размеры картинки не соответствуют макету.
5)  &#60;div id="right"&#62;  &#60;/div&#62; -зачем? Чтоб выровнять блок по центру используй margin: 0 auto;
1. "4) Размеры картинки не соответствуют макету." в задании не был указан размер фотки(может я пропустил)
   В задании написано сделать чтоб максимально соответствовало картинке.

**Comment by Mortehay** [comment]
поправил
по замечаниям "1", "2", "5"  - так у меня получился аналог - "margin: 0 auto;"(сделал три div, и получил много лишнего кода)

**Comment by AndriiLitvin** [comment]
Вообще намного лучше, но есть еще замечания..
1) Добавь border-radius картинке.
2)http://joxi.ru/v29l3qWF1OvgmG

По коду:
1) Нет  "< title >< /title >"
2)Присваиваешь тегам css, лучше делай через class=" ". 
3)"< div class='border' >" не нужно создавать еще один "div" добавь класс верхнему
4) И все таки лучше сделать все размеры в px так как на разных экранах будет выглядеть по разному. http://joxi.ru/V2VKbPBC9aPwAv , http://joxi.ru/DrlVgZQupJgG2P .
Сделай фиксированую верстку.
Вот посмотри в чем разница http://shpargalkablog.ru/2013/06/layout.html

**Comment by Mortehay** [comment]
поправил
с "4)" нужно еще поиграться

**Comment by AndriiLitvin** [comment]
исправляй "4)" и будет зачет

**Comment by Mortehay** [comment]
Наверное я неправильно выразился. "4)" - я поправил - поставил все размеры в px.

Я про ссылку -" http://shpargalkablog.ru/2013/06/layout.html" говорил, что нужно поиграться.

**Comment by AndriiLitvin** [comment]
http://joxi.ru/brR6zPlugRePr1

1)Отступы, нужно подогнать https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png
2) Где ссылка на фейсбук поменяй на fb.com

**Comment by Mortehay** [comment]
размеры мерял в photoshop :)
