### ISSUE TITLE
Замечания по работе 5.1

### ISSUE THREAD

**Issue by AndriiLitvin** [Mortehay/Mortehay.github.io#4]
http://joxi.ru/Y2L0zPXsR0Nw26
1)Тут не при ховере должно быть а при фокусе+текст в середине интпута через placeholder http://htmlbook.ru/html/input/placeholder
2)Здесь бекграунтд постоянный
3)НЕт бордера
4)Цвет текста не должен быть прозрачный
5)Кнопка не та. цвет бекграунда и текста отличаются
6)сайт должен быть на всю ширину
7)Бордер шире и цвет
8)Расстояние между флажком и текстом
9)При ховере должен быть отступ от текста

**Comment by AndriiLitvin** [comment]
http://joxi.ru/vAWZzP3sYKLd2W
1)Фокус чутка не такой как на макете. там вокруг белое свичение
2)Отцентрировать
3)Кнопку сделал не правильно. 
-назнач класс тегу "а" стрелочку и букву сделай через :before и :after
-тегу а назначаешь position:relative;
-before after position:absolute;
В общем сделай кнопку через классы css
4)Бордер толще
5)отцентрируй по вертикали
6)там еще есть картинка на фоне присмотрись к макету

**Comment by Mortehay** [comment]
исправил

**Comment by AndriiLitvin** [comment]
http://joxi.ru/bmoVE3Wu6ek0ry
в целом хорошо, только исправь:
1) бордер там цвет не тот.
2) отцентрируй и бордеры  больше. глянь на макет там вровень с кногпкой и инпутом

**Comment by Mortehay** [comment]
подправил

**Comment by AndriiLitvin** [comment]
вот это http://joxi.ru/MAjlEL1FvRXZ1m все форма. то что обведено нужно поместить в тег form. там поменяется чутка структура кода. и лишками конечно можно делать. но тут по логике больше div  подойдет

**Comment by Mortehay** [comment]
подправил

**Comment by AndriiLitvin** [comment]
## http://joxi.ru/xAe0gQ1sYJKNZ2

1) убрать точки
2)растянуть на ширину хедера

**Comment by AndriiLitvin** [comment]
## http://joxi.ru/n2Y5gPkSjGv6P2

1) вот так старайся не делать  .top_panel div назначай все через классы. так как вот это действует на все div внутри блока с классом top_panel. и чтоб перебить нужно большую цепочку писать.

напиши вот так:


 <div class="top_panel">

```
        <div class="top_panel_wrapper">

            <div class="float_right">

                <ul>
                    <li><a href="">Meu YouBike</a></li>
                    <li><a href="">Vender</a></li>
                    <li><a href="">Forum</a></li>
                    <li><a href="">Centato</a></li>
                    <li><a href="">Ajuda</a></li>
                </ul>
                <div class="top_panel_m_border">
                    <div><img src="img/flag.png" alt="flag"></div>
                    <div><p>Minhas Ofertas</p></div>
                </div>
                <div class="button">
                    <a href="" title="Ola">Ola <span>Entrar</span> ou <span>Cadastre-se</span></a>
                </div>
            </div>
        </div>  
    </div>
```

> >   div.top_panel div.top_panel_wrapper  {
> >         width: 1215px;
> >         height: 36px;
> >         display: block;
> >         float: none;
> >         margin: 0 auto;
> >     }
> >     .top_panel .top_panel_wrapper div.float_right {float: right;}

**Comment by Mortehay** [comment]
внес изменения, вижу у меня пока явные проблемы с marging/padding/float. отссыл к "посмотри видео" не поможет, тут надо самому научится ездить  на велосипеде,

**Comment by AndriiLitvin** [comment]
Зачет
