### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [Mortehay/Mortehay.github.io#7]
1. сделать 9 работу так как зачет получишь только тогда когда все эти работы будут. 
## 2. экран 320 http://joxi.ru/5mdMgP7iv4Zyg2

--http://joxi.ru/vAWZzP3skjXeV2
1) лого не по центру
2) когда наводишь на менюшку пропадает ховер на пункте "home"
3)слишком большой отступ от менюшки к слайдеру. там когда наводишь на меню слайдер дролжен перекрываться.
4)текст в слайдере не влазит шрифтов вообще нет прописаных в медиа квери
5) навигация(кружочки внизу слайдера) не по центру и их можно сделать через css
--http://joxi.ru/ZrJyzPXs130GGA
6)картинки чутка обрезаются и их нужно сделать через спрайты
7)font-family: OpenSans;
--http://joxi.ru/V2VKbPBC0ELZwA 
8)не влазит в экран
9) повторяется навигация, сделай через css
--http://joxi.ru/gmvgpyqtxyJoM2
10) отступы не те.
--http://joxi.ru/zANVzPDulJ59pA
11) опять же отступы и выравнивание
## 3. экран 480 http://joxi.ru/p277aN5s03jaY2

--http://joxi.ru/5mdMgP7iv4ZXa2
1)фон у слайдера светлее
2)текст не соответствует макету
3)навигация слайдера должна быть внизу и второй кружок активный
4)под телефоном тень
5)http://joxi.ru/Vm67Z8QsxVEej2 - тоже самое что и в 320
6) http://joxi.ru/823pdlkF6nGeXA -тоже что у 320
7)http://joxi.ru/l2Z64PNu8DM9y2 - отцентрировать
8) в футере http://joxi.ru/YmEDzPnuZbapgr два text-shadow
## 4 . Экран 768 http://joxi.ru/v29l3qWFGdk0qm

--http://joxi.ru/82Q5BPYS1DqYk2
1)отстум между менюшкой и слайдером большой
2)текст не такой ширины и его меньше
3)тень под айфоном
4)http://joxi.ru/D2PQzPDHdj47LA - ширина меньше. сделать картинки через спрайты
5)http://joxi.ru/a2XQzB3Hy0KxaA - поехало и в навигации второй кружок активный
--http://joxi.ru/L21b6x0F6GJGkA
6)text-shadow у заголовка.
7)ширина в блоке  меньше
8)текста меньше + он обрезается.
## 5. Экран 960 http://joxi.ru/LmGD9PEuR4LJJ2

1)ширина текста 
2)там тень есть
3)светлее фон
4)активный
5)нет треугольника
6)отступы
7)повторение и второй активный сделай через css
8) 9) отступы
10) text-shadow
11) все блочные бекграунды на всю страницу

**Comment by AndriiLitvin** [comment]
у тебя не правильно медиаквери прописаны. судя по 

## вебинару https://www.youtube.com/watch?v=UUsj9Q6y1CY

то нужно 320-479(макет 320), 480-767(макет 480), 768-959(макет 768), 960(макет 960)+

у тебя когда ширина 321 то появляются айфоны которых там не должно быть. по логике нужно переделать как я написал.

**Comment by AndriiLitvin** [comment]
## смотрю на Firefox
- http://joxi.ru/EA4vLykFDDxbKm - при большом экране все едет. сделай контейнер фиксированой ширины. на верстке макета 960+
- в оценку в экрамен входит 7-8-9 работа тобиж все вместе в одном таске.
- По всем макету   text-shadow
- стиль кода не совсем соответствует ТЗ. http://joxi.ru/ZrJyzPXs11D3kA
- div.lower_content_text>p {
  line-height: 150%;-тут в пикселях или просто 1, 2, 3 ...
  position: relative;
  top: -6px;
  left: -6px;
  } так не лучший вариант телать + если БЭМ то так не делается(ну у тебя не совсем БЭМ). Идет фон потом контейнер с определенной шириной потом сам контент.

## Экран 960 http://joxi.ru/vAWZzP3skkVYd2

1)Все оцетнрировать. решит так же как и в пятой работе.
2)Сбоку вот такое.  убрать.
3)4) поехало
5) обрезало
6)отцентрировать

## экран 768 http://joxi.ru/823pdlkF66394A

тут сам видишь поехало порезало

## экран 480 http://joxi.ru/8AnVER6uqqW78A 

1)ОТцентрировать
2)стрелочка поехала
3)везде горизонтальный скрол из за этого
4)на экранах по которым есть в архиве макеты должна быть пиксельная точность
5)обрезало
6)отцентрировать

## Экран 320 http://joxi.ru/vAWZzP3skklOE2

1) отцентрировать + предыдущие правки

**Comment by Mortehay** [comment]
стиль кода не совсем соответствует ТЗ. http://joxi.ru/ZrJyzPXs11D3kA  ты хочеш моей смерти :)
исправлю, центрировать не ад, ад IE :), в первом(выравнивание) случае это я глупый, во втором оба

**Comment by AndriiLitvin** [comment]
http://joxi.ru/bmoVE3WuMMvepr - на больших экранах все лезет. задай при больших экранах max-width

## вот так видит мозила ширина 960  http://joxi.ru/L21b6x0F66y4GA

+по всему макету text-shadow

1)сделай флоат райт убери паддинг и добавь верхний марджин. должно быть норм
2)3) поплыло вверх
4)не понятная область. убери ее, так как из за нее появляется горизонтальный скрол
5)text-shadow: 0px 1px 0px #0f1518;
6)7)все полезло текст не тот. не такой жирный и text-shadow: 0px 1px 0px #ffffff;
8) первую колонку с контентом заменить на ту что в макете 960 ,
 текст не жирный там text-shadow: 0px 1px 0px #ffffff; font-family: OpenSans; а заголовки font-family: LeagueGothic;- это по всему макету

замечания по внешнему виду на всех экранах(пересмотри)

код.. 

> стиль кода не совсем соответствует ТЗ. http://joxi.ru/ZrJyzPXs11D3kA ты хочеш моей смерти :)
> исправлю, центрировать не ад, ад IE :), в первом(выравнивание) случае это я глупый, во втором оба

мне не жалко я могу поставить зачет. но ТЗ есть ТЗ. и прописывай всем элементам классы. и не делай жёсткую привязку ну тип такого div.header_content>div>p делаешь р класс и все свойства туда. просто чтоб не было копипаста стилей и оно намного приятнее выглядит. на счет БЭМ там особо страшного ничего нет. Просто я хз. если я приму такую работу у тебя не вылезит ли это мне боком. + хочется чтоб вы все выпустились и все могли и к всему были готовы))
